# PostgreSQL configuration for Binge Watching
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgres://postgres:postgres@localhost:5432/binge_watching_development") %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgres://postgres:postgres@localhost:5432/binge_watching_test").gsub("development", "test") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
